---
title: "Proyecto Final Modelos no parametricos y de regresión"
author: "Gómez Jiménez Aaron Mauricio"
date: "2023-05-17"
output: html_document
pdf_document: default

---

```{r setup, include=FALSE}

library(readxl)
library(dplyr)
library(ggplot2)
library(lmtest)
library(corrplot)
library(tidyverse)

```

Primero cargamos los adatos y al observar que existe un dato faltante decidimos quitarlo ya que al tener una base de 158 datos, consideramos que que nuestra base sigue siendo grande y buena para trabajar.

```{r, include=FALSE, message=FALSE, results=F}
base = read.csv("inflama.csv")
data= data.frame(base)
datos=data
datos1=na.omit(datos)
head(datos1)
```

Hacemos un resumen de los datos para observar los maximos y minimos 

```{r}
summary(datos1)
```

```{r}
reg1=lm(razon_ad.lep~.,datos)
summary(reg1)
```

```{r}
pairs(datos1)
datos1 |>
  GGally::ggpairs()
```

```{r}
modelo_full <- lm(razon_ad.lep ~ ., datos)

modelo_nulo <- lm(razon_ad.lep ~ 1, datos1)
summary(modelo_nulo)

# Paso 1

tabla1_add1 <- add1(
  modelo_nulo, 
  test  = "F",
  scope = formula(modelo_full)
)

modelo_add1 <- lm(
  razon_ad.lep ~ escol_madre, 
  datos
)
summary(modelo_add1)

# Paso 2

tabla2_add1 <- add1(
  modelo_add1, 
  test  = "F",
  scope = formula(modelo_full)
)

# ya no hay variables significativas
```

